// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: api/nous/v1/nous.proto

package nousv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Nous_Extract_FullMethodName             = "/nous.v1.Nous/Extract"
	Nous_Evaluate_FullMethodName            = "/nous.v1.Nous/Evaluate"
	Nous_ListCommitments_FullMethodName     = "/nous.v1.Nous/ListCommitments"
	Nous_GetCommitment_FullMethodName       = "/nous.v1.Nous/GetCommitment"
	Nous_ListDecisions_FullMethodName       = "/nous.v1.Nous/ListDecisions"
	Nous_GetDecision_FullMethodName         = "/nous.v1.Nous/GetDecision"
	Nous_ListInterventions_FullMethodName   = "/nous.v1.Nous/ListInterventions"
	Nous_GetIntervention_FullMethodName     = "/nous.v1.Nous/GetIntervention"
	Nous_ResolveIntervention_FullMethodName = "/nous.v1.Nous/ResolveIntervention"
)

// NousClient is the client API for Nous service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Nous is the proactive commitment tracking and intervention service.
type NousClient interface {
	// Extract scans text for implied commitments and persists them.
	Extract(ctx context.Context, in *ExtractRequest, opts ...grpc.CallOption) (*ExtractResponse, error)
	// Evaluate runs the risk scoring and intervention loop over active
	// commitments.
	Evaluate(ctx context.Context, in *EvaluateRequest, opts ...grpc.CallOption) (*EvaluateResponse, error)
	// ListCommitments returns commitments matching the filter.
	ListCommitments(ctx context.Context, in *ListCommitmentsRequest, opts ...grpc.CallOption) (*ListCommitmentsResponse, error)
	// GetCommitment returns a single commitment by ID.
	GetCommitment(ctx context.Context, in *GetCommitmentRequest, opts ...grpc.CallOption) (*Commitment, error)
	// ListDecisions returns decisions for audit replay.
	ListDecisions(ctx context.Context, in *ListDecisionsRequest, opts ...grpc.CallOption) (*ListDecisionsResponse, error)
	// GetDecision returns a single decision by ID.
	GetDecision(ctx context.Context, in *GetDecisionRequest, opts ...grpc.CallOption) (*Decision, error)
	// ListInterventions returns interventions matching the filter.
	ListInterventions(ctx context.Context, in *ListInterventionsRequest, opts ...grpc.CallOption) (*ListInterventionsResponse, error)
	// GetIntervention returns a single intervention by ID.
	GetIntervention(ctx context.Context, in *GetInterventionRequest, opts ...grpc.CallOption) (*Intervention, error)
	// ResolveIntervention transitions an intervention to a terminal state.
	ResolveIntervention(ctx context.Context, in *ResolveInterventionRequest, opts ...grpc.CallOption) (*Intervention, error)
}

type nousClient struct {
	cc grpc.ClientConnInterface
}

func NewNousClient(cc grpc.ClientConnInterface) NousClient {
	return &nousClient{cc}
}

func (c *nousClient) Extract(ctx context.Context, in *ExtractRequest, opts ...grpc.CallOption) (*ExtractResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtractResponse)
	err := c.cc.Invoke(ctx, Nous_Extract_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nousClient) Evaluate(ctx context.Context, in *EvaluateRequest, opts ...grpc.CallOption) (*EvaluateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateResponse)
	err := c.cc.Invoke(ctx, Nous_Evaluate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nousClient) ListCommitments(ctx context.Context, in *ListCommitmentsRequest, opts ...grpc.CallOption) (*ListCommitmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCommitmentsResponse)
	err := c.cc.Invoke(ctx, Nous_ListCommitments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nousClient) GetCommitment(ctx context.Context, in *GetCommitmentRequest, opts ...grpc.CallOption) (*Commitment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Commitment)
	err := c.cc.Invoke(ctx, Nous_GetCommitment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nousClient) ListDecisions(ctx context.Context, in *ListDecisionsRequest, opts ...grpc.CallOption) (*ListDecisionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDecisionsResponse)
	err := c.cc.Invoke(ctx, Nous_ListDecisions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nousClient) GetDecision(ctx context.Context, in *GetDecisionRequest, opts ...grpc.CallOption) (*Decision, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Decision)
	err := c.cc.Invoke(ctx, Nous_GetDecision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nousClient) ListInterventions(ctx context.Context, in *ListInterventionsRequest, opts ...grpc.CallOption) (*ListInterventionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInterventionsResponse)
	err := c.cc.Invoke(ctx, Nous_ListInterventions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nousClient) GetIntervention(ctx context.Context, in *GetInterventionRequest, opts ...grpc.CallOption) (*Intervention, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Intervention)
	err := c.cc.Invoke(ctx, Nous_GetIntervention_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nousClient) ResolveIntervention(ctx context.Context, in *ResolveInterventionRequest, opts ...grpc.CallOption) (*Intervention, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Intervention)
	err := c.cc.Invoke(ctx, Nous_ResolveIntervention_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NousServer is the server API for Nous service.
// All implementations must embed UnimplementedNousServer
// for forward compatibility.
//
// Nous is the proactive commitment tracking and intervention service.
type NousServer interface {
	// Extract scans text for implied commitments and persists them.
	Extract(context.Context, *ExtractRequest) (*ExtractResponse, error)
	// Evaluate runs the risk scoring and intervention loop over active
	// commitments.
	Evaluate(context.Context, *EvaluateRequest) (*EvaluateResponse, error)
	// ListCommitments returns commitments matching the filter.
	ListCommitments(context.Context, *ListCommitmentsRequest) (*ListCommitmentsResponse, error)
	// GetCommitment returns a single commitment by ID.
	GetCommitment(context.Context, *GetCommitmentRequest) (*Commitment, error)
	// ListDecisions returns decisions for audit replay.
	ListDecisions(context.Context, *ListDecisionsRequest) (*ListDecisionsResponse, error)
	// GetDecision returns a single decision by ID.
	GetDecision(context.Context, *GetDecisionRequest) (*Decision, error)
	// ListInterventions returns interventions matching the filter.
	ListInterventions(context.Context, *ListInterventionsRequest) (*ListInterventionsResponse, error)
	// GetIntervention returns a single intervention by ID.
	GetIntervention(context.Context, *GetInterventionRequest) (*Intervention, error)
	// ResolveIntervention transitions an intervention to a terminal state.
	ResolveIntervention(context.Context, *ResolveInterventionRequest) (*Intervention, error)
	mustEmbedUnimplementedNousServer()
}

// UnimplementedNousServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNousServer struct{}

func (UnimplementedNousServer) Extract(context.Context, *ExtractRequest) (*ExtractResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Extract not implemented")
}
func (UnimplementedNousServer) Evaluate(context.Context, *EvaluateRequest) (*EvaluateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Evaluate not implemented")
}
func (UnimplementedNousServer) ListCommitments(context.Context, *ListCommitmentsRequest) (*ListCommitmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCommitments not implemented")
}
func (UnimplementedNousServer) GetCommitment(context.Context, *GetCommitmentRequest) (*Commitment, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCommitment not implemented")
}
func (UnimplementedNousServer) ListDecisions(context.Context, *ListDecisionsRequest) (*ListDecisionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDecisions not implemented")
}
func (UnimplementedNousServer) GetDecision(context.Context, *GetDecisionRequest) (*Decision, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDecision not implemented")
}
func (UnimplementedNousServer) ListInterventions(context.Context, *ListInterventionsRequest) (*ListInterventionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInterventions not implemented")
}
func (UnimplementedNousServer) GetIntervention(context.Context, *GetInterventionRequest) (*Intervention, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIntervention not implemented")
}
func (UnimplementedNousServer) ResolveIntervention(context.Context, *ResolveInterventionRequest) (*Intervention, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveIntervention not implemented")
}
func (UnimplementedNousServer) mustEmbedUnimplementedNousServer() {}
func (UnimplementedNousServer) testEmbeddedByValue()              {}

// UnsafeNousServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NousServer will
// result in compilation errors.
type UnsafeNousServer interface {
	mustEmbedUnimplementedNousServer()
}

func RegisterNousServer(s grpc.ServiceRegistrar, srv NousServer) {
	// If the following call panics, it indicates UnimplementedNousServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Nous_ServiceDesc, srv)
}

func _Nous_Extract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NousServer).Extract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nous_Extract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NousServer).Extract(ctx, req.(*ExtractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nous_Evaluate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NousServer).Evaluate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nous_Evaluate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NousServer).Evaluate(ctx, req.(*EvaluateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nous_ListCommitments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommitmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NousServer).ListCommitments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nous_ListCommitments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NousServer).ListCommitments(ctx, req.(*ListCommitmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nous_GetCommitment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommitmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NousServer).GetCommitment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nous_GetCommitment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NousServer).GetCommitment(ctx, req.(*GetCommitmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nous_ListDecisions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDecisionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NousServer).ListDecisions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nous_ListDecisions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NousServer).ListDecisions(ctx, req.(*ListDecisionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nous_GetDecision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NousServer).GetDecision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nous_GetDecision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NousServer).GetDecision(ctx, req.(*GetDecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nous_ListInterventions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInterventionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NousServer).ListInterventions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nous_ListInterventions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NousServer).ListInterventions(ctx, req.(*ListInterventionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nous_GetIntervention_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInterventionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NousServer).GetIntervention(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nous_GetIntervention_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NousServer).GetIntervention(ctx, req.(*GetInterventionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nous_ResolveIntervention_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveInterventionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NousServer).ResolveIntervention(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nous_ResolveIntervention_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NousServer).ResolveIntervention(ctx, req.(*ResolveInterventionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Nous_ServiceDesc is the grpc.ServiceDesc for Nous service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Nous_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nous.v1.Nous",
	HandlerType: (*NousServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Extract",
			Handler:    _Nous_Extract_Handler,
		},
		{
			MethodName: "Evaluate",
			Handler:    _Nous_Evaluate_Handler,
		},
		{
			MethodName: "ListCommitments",
			Handler:    _Nous_ListCommitments_Handler,
		},
		{
			MethodName: "GetCommitment",
			Handler:    _Nous_GetCommitment_Handler,
		},
		{
			MethodName: "ListDecisions",
			Handler:    _Nous_ListDecisions_Handler,
		},
		{
			MethodName: "GetDecision",
			Handler:    _Nous_GetDecision_Handler,
		},
		{
			MethodName: "ListInterventions",
			Handler:    _Nous_ListInterventions_Handler,
		},
		{
			MethodName: "GetIntervention",
			Handler:    _Nous_GetIntervention_Handler,
		},
		{
			MethodName: "ResolveIntervention",
			Handler:    _Nous_ResolveIntervention_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/nous/v1/nous.proto",
}
