// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/nous/v1/nous.proto

package nousv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExtractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Hints         []string               `protobuf:"bytes,3,rep,name=hints,proto3" json:"hints,omitempty"`
	SourceRefs    []*SourceRef           `protobuf:"bytes,4,rep,name=source_refs,json=sourceRefs,proto3" json:"source_refs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractRequest) Reset() {
	*x = ExtractRequest{}
	mi := &file_api_nous_v1_nous_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractRequest) ProtoMessage() {}

func (x *ExtractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_nous_v1_nous_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractRequest.ProtoReflect.Descriptor instead.
func (*ExtractRequest) Descriptor() ([]byte, []int) {
	return file_api_nous_v1_nous_proto_rawDescGZIP(), []int{0}
}

func (x *ExtractRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *ExtractRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ExtractRequest) GetHints() []string {
	if x != nil {
		return x.Hints
	}
	return nil
}

func (x *ExtractRequest) GetSourceRefs() []*SourceRef {
	if x != nil {
		return x.SourceRefs
	}
	return nil
}

type ExtractResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Considered    int32                  `protobuf:"varint,1,opt,name=considered,proto3" json:"considered,omitempty"`
	SavedIds      []string               `protobuf:"bytes,2,rep,name=saved_ids,json=savedIds,proto3" json:"saved_ids,omitempty"`
	Dropped       int32                  `protobuf:"varint,3,opt,name=dropped,proto3" json:"dropped,omitempty"`
	DecisionId    string                 `protobuf:"bytes,4,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractResponse) Reset() {
	*x = ExtractResponse{}
	mi := &file_api_nous_v1_nous_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractResponse) ProtoMessage() {}

func (x *ExtractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_nous_v1_nous_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractResponse.ProtoReflect.Descriptor instead.
func (*ExtractResponse) Descriptor() ([]byte, []int) {
	return file_api_nous_v1_nous_proto_rawDescGZIP(), []int{1}
}

func (x *ExtractResponse) GetConsidered() int32 {
	if x != nil {
		return x.Considered
	}
	return 0
}

func (x *ExtractResponse) GetSavedIds() []string {
	if x != nil {
		return x.SavedIds
	}
	return nil
}

func (x *ExtractResponse) GetDropped() int32 {
	if x != nil {
		return x.Dropped
	}
	return 0
}

func (x *ExtractResponse) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

type EvaluateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Limit          int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	SignalLookback *durationpb.Duration   `protobuf:"bytes,2,opt,name=signal_lookback,json=signalLookback,proto3" json:"signal_lookback,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EvaluateRequest) Reset() {
	*x = EvaluateRequest{}
	mi := &file_api_nous_v1_nous_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRequest) ProtoMessage() {}

func (x *EvaluateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_nous_v1_nous_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRequest.ProtoReflect.Descriptor instead.
func (*EvaluateRequest) Descriptor() ([]byte, []int) {
	return file_api_nous_v1_nous_proto_rawDescGZIP(), []int{2}
}

func (x *EvaluateRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *EvaluateRequest) GetSignalLookback() *durationpb.Duration {
	if x != nil {
		return x.SignalLookback
	}
	return nil
}

type EvaluateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Evaluated       int32                  `protobuf:"varint,1,opt,name=evaluated,proto3" json:"evaluated,omitempty"`
	Updated         int32                  `protobuf:"varint,2,opt,name=updated,proto3" json:"updated,omitempty"`
	InterventionIds []string               `protobuf:"bytes,3,rep,name=intervention_ids,json=interventionIds,proto3" json:"intervention_ids,omitempty"`
	DecisionIds     []string               `protobuf:"bytes,4,rep,name=decision_ids,json=decisionIds,proto3" json:"decision_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EvaluateResponse) Reset() {
	*x = EvaluateResponse{}
	mi := &file_api_nous_v1_nous_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateResponse) ProtoMessage() {}

func (x *EvaluateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_nous_v1_nous_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateResponse.ProtoReflect.Descriptor instead.
func (*EvaluateResponse) Descriptor() ([]byte, []int) {
	return file_api_nous_v1_nous_proto_rawDescGZIP(), []int{3}
}

func (x *EvaluateResponse) GetEvaluated() int32 {
	if x != nil {
		return x.Evaluated
	}
	return 0
}

func (x *EvaluateResponse) GetUpdated() int32 {
	if x != nil {
		return x.Updated
	}
	return 0
}

func (x *EvaluateResponse) GetInterventionIds() []string {
	if x != nil {
		return x.InterventionIds
	}
	return nil
}

func (x *EvaluateResponse) GetDecisionIds() []string {
	if x != nil {
		return x.DecisionIds
	}
	return nil
}

type ListCommitmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Statuses      []string               `protobuf:"bytes,2,rep,name=statuses,proto3" json:"statuses,omitempty"`
	DueBy         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=due_by,json=dueBy,proto3" json:"due_by,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommitmentsRequest) Reset() {
	*x = ListCommitmentsRequest{}
	mi := &file_api_nous_v1_nous_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommitmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommitmentsRequest) ProtoMessage() {}

func (x *ListCommitmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_nous_v1_nous_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommitmentsRequest.ProtoReflect.Descriptor instead.
func (*ListCommitmentsRequest) Descriptor() ([]byte, []int) {
	return file_api_nous_v1_nous_proto_rawDescGZIP(), []int{4}
}

func (x *ListCommitmentsRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *ListCommitmentsRequest) GetStatuses() []string {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *ListCommitmentsRequest) GetDueBy() *timestamppb.Timestamp {
	if x != nil {
		return x.DueBy
	}
	return nil
}

func (x *ListCommitmentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListCommitmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commitments   []*Commitment          `protobuf:"bytes,1,rep,name=commitments,proto3" json:"commitments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommitmentsResponse) Reset() {
	*x = ListCommitmentsResponse{}
	mi := &file_api_nous_v1_nous_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommitmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommitmentsResponse) ProtoMessage() {}

func (x *ListCommitmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_nous_v1_nous_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommitmentsResponse.ProtoReflect.Descriptor instead.
func (*ListCommitmentsResponse) Descriptor() ([]byte, []int) {
	return file_api_nous_v1_nous_proto_rawDescGZIP(), []int{5}
}

func (x *ListCommitmentsResponse) GetCommitments() []*Commitment {
	if x != nil {
		return x.Commitments
	}
	return nil
}

type GetCommitmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommitmentRequest) Reset() {
	*x = GetCommitmentRequest{}
	mi := &file_api_nous_v1_nous_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommitmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommitmentRequest) ProtoMessage() {}

func (x *GetCommitmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_nous_v1_nous_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommitmentRequest.ProtoReflect.Descriptor instead.
func (*GetCommitmentRequest) Descriptor() ([]byte, []int) {
	return file_api_nous_v1_nous_proto_rawDescGZIP(), []int{6}
}

func (x *GetCommitmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Commitment struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId         string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	SourceRefs      []*SourceRef           `protobuf:"bytes,4,rep,name=source_refs,json=sourceRefs,proto3" json:"source_refs,omitempty"`
	Entities        []*EntityRef           `protobuf:"bytes,5,rep,name=entities,proto3" json:"entities,omitempty"`
	DueAt           *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=due_at,json=dueAt,proto3" json:"due_at,omitempty"`
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Confidence      float64                `protobuf:"fixed64,8,opt,name=confidence,proto3" json:"confidence,omitempty"`
	RiskScore       float64                `protobuf:"fixed64,9,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	LastEvaluatedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_evaluated_at,json=lastEvaluatedAt,proto3" json:"last_evaluated_at,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Commitment) Reset() {
	*x = Commitment{}
	mi := &file_api_nous_v1_nous_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Commitment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commitment) ProtoMessage() {}

func (x *Commitment) ProtoReflect() protoreflect.Message {
	mi := &file_api_nous_v1_nous_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commitment.ProtoReflect.Descriptor instead.
func (*Commitment) Descriptor() ([]byte, []int) {
	return file_api_nous_v1_nous_proto_rawDescGZIP(), []int{7}
}

func (x *Commitment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Commitment) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Commitment) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Commitment) GetSourceRefs() []*SourceRef {
	if x != nil {
		return x.SourceRefs
	}
	return nil
}

func (x *Commitment) GetEntities() []*EntityRef {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *Commitment) GetDueAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DueAt
	}
	return nil
}

func (x *Commitment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Commitment) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Commitment) GetRiskScore() float64 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *Commitment) GetLastEvaluatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastEvaluatedAt
	}
	return nil
}

func (x *Commitment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Commitment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListDecisionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDecisionsRequest) Reset() {
	*x = ListDecisionsRequest{}
	mi := &file_api_nous_v1_nous_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDecisionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDecisionsRequest) ProtoMessage() {}

func (x *ListDecisionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_nous_v1_nous_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDecisionsRequest.ProtoReflect.Descriptor instead.
func (*ListDecisionsRequest) Descriptor() ([]byte, []int) {
	return file_api_nous_v1_nous_proto_rawDescGZIP(), []int{8}
}

func (x *ListDecisionsRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *ListDecisionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListDecisionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decisions     []*Decision            `protobuf:"bytes,1,rep,name=decisions,proto3" json:"decisions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDecisionsResponse) Reset() {
	*x = ListDecisionsResponse{}
	mi := &file_api_nous_v1_nous_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDecisionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDecisionsResponse) ProtoMessage() {}

func (x *ListDecisionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_nous_v1_nous_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDecisionsResponse.ProtoReflect.Descriptor instead.
func (*ListDecisionsResponse) Descriptor() ([]byte, []int) {
	return file_api_nous_v1_nous_proto_rawDescGZIP(), []int{9}
}

func (x *ListDecisionsResponse) GetDecisions() []*Decision {
	if x != nil {
		return x.Decisions
	}
	return nil
}

type GetDecisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDecisionRequest) Reset() {
	*x = GetDecisionRequest{}
	mi := &file_api_nous_v1_nous_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDecisionRequest) ProtoMessage() {}

func (x *GetDecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_nous_v1_nous_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDecisionRequest.ProtoReflect.Descriptor instead.
func (*GetDecisionRequest) Descriptor() ([]byte, []int) {
	return file_api_nous_v1_nous_proto_rawDescGZIP(), []int{10}
}

func (x *GetDecisionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Decision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	ContextRefs   []*SourceRef           `protobuf:"bytes,3,rep,name=context_refs,json=contextRefs,proto3" json:"context_refs,omitempty"`
	Inputs        map[string]string      `protobuf:"bytes,4,rep,name=inputs,proto3" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Outcome       map[string]string      `protobuf:"bytes,5,rep,name=outcome,proto3" json:"outcome,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	Confidence    float64                `protobuf:"fixed64,7,opt,name=confidence,proto3" json:"confidence,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Decision) Reset() {
	*x = Decision{}
	mi := &file_api_nous_v1_nous_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decision) ProtoMessage() {}

func (x *Decision) ProtoReflect() protoreflect.Message {
	mi := &file_api_nous_v1_nous_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decision.ProtoReflect.Descriptor instead.
func (*Decision) Descriptor() ([]byte, []int) {
	return file_api_nous_v1_nous_proto_rawDescGZIP(), []int{11}
}

func (x *Decision) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Decision) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Decision) GetContextRefs() []*SourceRef {
	if x != nil {
		return x.ContextRefs
	}
	return nil
}

func (x *Decision) GetInputs() map[string]string {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *Decision) GetOutcome() map[string]string {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *Decision) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Decision) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Decision) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListInterventionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommitmentId  string                 `protobuf:"bytes,1,opt,name=commitment_id,json=commitmentId,proto3" json:"commitment_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Statuses      []string               `protobuf:"bytes,3,rep,name=statuses,proto3" json:"statuses,omitempty"`
	Since         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=since,proto3" json:"since,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInterventionsRequest) Reset() {
	*x = ListInterventionsRequest{}
	mi := &file_api_nous_v1_nous_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInterventionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInterventionsRequest) ProtoMessage() {}

func (x *ListInterventionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_nous_v1_nous_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInterventionsRequest.ProtoReflect.Descriptor instead.
func (*ListInterventionsRequest) Descriptor() ([]byte, []int) {
	return file_api_nous_v1_nous_proto_rawDescGZIP(), []int{12}
}

func (x *ListInterventionsRequest) GetCommitmentId() string {
	if x != nil {
		return x.CommitmentId
	}
	return ""
}

func (x *ListInterventionsRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ListInterventionsRequest) GetStatuses() []string {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *ListInterventionsRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *ListInterventionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListInterventionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interventions []*Intervention        `protobuf:"bytes,1,rep,name=interventions,proto3" json:"interventions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInterventionsResponse) Reset() {
	*x = ListInterventionsResponse{}
	mi := &file_api_nous_v1_nous_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInterventionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInterventionsResponse) ProtoMessage() {}

func (x *ListInterventionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_nous_v1_nous_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInterventionsResponse.ProtoReflect.Descriptor instead.
func (*ListInterventionsResponse) Descriptor() ([]byte, []int) {
	return file_api_nous_v1_nous_proto_rawDescGZIP(), []int{13}
}

func (x *ListInterventionsResponse) GetInterventions() []*Intervention {
	if x != nil {
		return x.Interventions
	}
	return nil
}

type GetInterventionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInterventionRequest) Reset() {
	*x = GetInterventionRequest{}
	mi := &file_api_nous_v1_nous_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInterventionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInterventionRequest) ProtoMessage() {}

func (x *GetInterventionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_nous_v1_nous_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInterventionRequest.ProtoReflect.Descriptor instead.
func (*GetInterventionRequest) Descriptor() ([]byte, []int) {
	return file_api_nous_v1_nous_proto_rawDescGZIP(), []int{14}
}

func (x *GetInterventionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ResolveInterventionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // accepted, rejected, expired
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveInterventionRequest) Reset() {
	*x = ResolveInterventionRequest{}
	mi := &file_api_nous_v1_nous_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveInterventionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveInterventionRequest) ProtoMessage() {}

func (x *ResolveInterventionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_nous_v1_nous_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveInterventionRequest.ProtoReflect.Descriptor instead.
func (*ResolveInterventionRequest) Descriptor() ([]byte, []int) {
	return file_api_nous_v1_nous_proto_rawDescGZIP(), []int{15}
}

func (x *ResolveInterventionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResolveInterventionRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Intervention struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CommitmentId    string                 `protobuf:"bytes,2,opt,name=commitment_id,json=commitmentId,proto3" json:"commitment_id,omitempty"`
	TaskId          string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Type            string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Message         string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	SuggestedAction *ActionRequest         `protobuf:"bytes,6,opt,name=suggested_action,json=suggestedAction,proto3" json:"suggested_action,omitempty"`
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	TriggeredAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=triggered_at,json=triggeredAt,proto3" json:"triggered_at,omitempty"`
	ResolvedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=resolved_at,json=resolvedAt,proto3" json:"resolved_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Intervention) Reset() {
	*x = Intervention{}
	mi := &file_api_nous_v1_nous_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Intervention) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Intervention) ProtoMessage() {}

func (x *Intervention) ProtoReflect() protoreflect.Message {
	mi := &file_api_nous_v1_nous_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Intervention.ProtoReflect.Descriptor instead.
func (*Intervention) Descriptor() ([]byte, []int) {
	return file_api_nous_v1_nous_proto_rawDescGZIP(), []int{16}
}

func (x *Intervention) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Intervention) GetCommitmentId() string {
	if x != nil {
		return x.CommitmentId
	}
	return ""
}

func (x *Intervention) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Intervention) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Intervention) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Intervention) GetSuggestedAction() *ActionRequest {
	if x != nil {
		return x.SuggestedAction
	}
	return nil
}

func (x *Intervention) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Intervention) GetTriggeredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TriggeredAt
	}
	return nil
}

func (x *Intervention) GetResolvedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ResolvedAt
	}
	return nil
}

type SourceRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Locator       string                 `protobuf:"bytes,2,opt,name=locator,proto3" json:"locator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceRef) Reset() {
	*x = SourceRef{}
	mi := &file_api_nous_v1_nous_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceRef) ProtoMessage() {}

func (x *SourceRef) ProtoReflect() protoreflect.Message {
	mi := &file_api_nous_v1_nous_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceRef.ProtoReflect.Descriptor instead.
func (*SourceRef) Descriptor() ([]byte, []int) {
	return file_api_nous_v1_nous_proto_rawDescGZIP(), []int{17}
}

func (x *SourceRef) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *SourceRef) GetLocator() string {
	if x != nil {
		return x.Locator
	}
	return ""
}

type EntityRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityRef) Reset() {
	*x = EntityRef{}
	mi := &file_api_nous_v1_nous_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityRef) ProtoMessage() {}

func (x *EntityRef) ProtoReflect() protoreflect.Message {
	mi := &file_api_nous_v1_nous_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityRef.ProtoReflect.Descriptor instead.
func (*EntityRef) Descriptor() ([]byte, []int) {
	return file_api_nous_v1_nous_proto_rawDescGZIP(), []int{18}
}

func (x *EntityRef) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *EntityRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EntityRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ActionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Capability     string                 `protobuf:"bytes,2,opt,name=capability,proto3" json:"capability,omitempty"`
	Payload        map[string]string      `protobuf:"bytes,3,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Constraints    []*ActionConstraint    `protobuf:"bytes,4,rep,name=constraints,proto3" json:"constraints,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ActionRequest) Reset() {
	*x = ActionRequest{}
	mi := &file_api_nous_v1_nous_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionRequest) ProtoMessage() {}

func (x *ActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_nous_v1_nous_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionRequest.ProtoReflect.Descriptor instead.
func (*ActionRequest) Descriptor() ([]byte, []int) {
	return file_api_nous_v1_nous_proto_rawDescGZIP(), []int{19}
}

func (x *ActionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActionRequest) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *ActionRequest) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ActionRequest) GetConstraints() []*ActionConstraint {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *ActionRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type ActionConstraint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionConstraint) Reset() {
	*x = ActionConstraint{}
	mi := &file_api_nous_v1_nous_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionConstraint) ProtoMessage() {}

func (x *ActionConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_api_nous_v1_nous_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionConstraint.ProtoReflect.Descriptor instead.
func (*ActionConstraint) Descriptor() ([]byte, []int) {
	return file_api_nous_v1_nous_proto_rawDescGZIP(), []int{20}
}

func (x *ActionConstraint) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ActionConstraint) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_api_nous_v1_nous_proto protoreflect.FileDescriptor

const file_api_nous_v1_nous_proto_rawDesc = "" +
	"\n" +
	"\x16api/nous/v1/nous.proto\x12\anous.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\x8a\x01\n" +
	"\x0eExtractRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x14\n" +
	"\x05hints\x18\x03 \x03(\tR\x05hints\x123\n" +
	"\vsource_refs\x18\x04 \x03(\v2\x12.nous.v1.SourceRefR\n" +
	"sourceRefs\"\x89\x01\n" +
	"\x0fExtractResponse\x12\x1e\n" +
	"\n" +
	"considered\x18\x01 \x01(\x05R\n" +
	"considered\x12\x1b\n" +
	"\tsaved_ids\x18\x02 \x03(\tR\bsavedIds\x12\x18\n" +
	"\adropped\x18\x03 \x01(\x05R\adropped\x12\x1f\n" +
	"\vdecision_id\x18\x04 \x01(\tR\n" +
	"decisionId\"k\n" +
	"\x0fEvaluateRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12B\n" +
	"\x0fsignal_lookback\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x0esignalLookback\"\x98\x01\n" +
	"\x10EvaluateResponse\x12\x1c\n" +
	"\tevaluated\x18\x01 \x01(\x05R\tevaluated\x12\x18\n" +
	"\aupdated\x18\x02 \x01(\x05R\aupdated\x12)\n" +
	"\x10intervention_ids\x18\x03 \x03(\tR\x0finterventionIds\x12!\n" +
	"\fdecision_ids\x18\x04 \x03(\tR\vdecisionIds\"\x98\x01\n" +
	"\x16ListCommitmentsRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x1a\n" +
	"\bstatuses\x18\x02 \x03(\tR\bstatuses\x121\n" +
	"\x06due_by\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05dueBy\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"P\n" +
	"\x17ListCommitmentsResponse\x125\n" +
	"\vcommitments\x18\x01 \x03(\v2\x13.nous.v1.CommitmentR\vcommitments\"&\n" +
	"\x14GetCommitmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x86\x04\n" +
	"\n" +
	"Commitment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x123\n" +
	"\vsource_refs\x18\x04 \x03(\v2\x12.nous.v1.SourceRefR\n" +
	"sourceRefs\x12.\n" +
	"\bentities\x18\x05 \x03(\v2\x12.nous.v1.EntityRefR\bentities\x121\n" +
	"\x06due_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x05dueAt\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"confidence\x18\b \x01(\x01R\n" +
	"confidence\x12\x1d\n" +
	"\n" +
	"risk_score\x18\t \x01(\x01R\triskScore\x12F\n" +
	"\x11last_evaluated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x0flastEvaluatedAt\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"F\n" +
	"\x14ListDecisionsRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"H\n" +
	"\x15ListDecisionsResponse\x12/\n" +
	"\tdecisions\x18\x01 \x03(\v2\x11.nous.v1.DecisionR\tdecisions\"$\n" +
	"\x12GetDecisionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xc6\x03\n" +
	"\bDecision\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x125\n" +
	"\fcontext_refs\x18\x03 \x03(\v2\x12.nous.v1.SourceRefR\vcontextRefs\x125\n" +
	"\x06inputs\x18\x04 \x03(\v2\x1d.nous.v1.Decision.InputsEntryR\x06inputs\x128\n" +
	"\aoutcome\x18\x05 \x03(\v2\x1e.nous.v1.Decision.OutcomeEntryR\aoutcome\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x12\x1e\n" +
	"\n" +
	"confidence\x18\a \x01(\x01R\n" +
	"confidence\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x1a9\n" +
	"\vInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fOutcomeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbc\x01\n" +
	"\x18ListInterventionsRequest\x12#\n" +
	"\rcommitment_id\x18\x01 \x01(\tR\fcommitmentId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1a\n" +
	"\bstatuses\x18\x03 \x03(\tR\bstatuses\x120\n" +
	"\x05since\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"X\n" +
	"\x19ListInterventionsResponse\x12;\n" +
	"\rinterventions\x18\x01 \x03(\v2\x15.nous.v1.InterventionR\rinterventions\"(\n" +
	"\x16GetInterventionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\x1aResolveInterventionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xe1\x02\n" +
	"\fIntervention\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rcommitment_id\x18\x02 \x01(\tR\fcommitmentId\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12A\n" +
	"\x10suggested_action\x18\x06 \x01(\v2\x16.nous.v1.ActionRequestR\x0fsuggestedAction\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12=\n" +
	"\ftriggered_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vtriggeredAt\x12;\n" +
	"\vresolved_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"resolvedAt\"9\n" +
	"\tSourceRef\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x18\n" +
	"\alocator\x18\x02 \x01(\tR\alocator\"C\n" +
	"\tEntityRef\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"\xa0\x02\n" +
	"\rActionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\n" +
	"capability\x18\x02 \x01(\tR\n" +
	"capability\x12=\n" +
	"\apayload\x18\x03 \x03(\v2#.nous.v1.ActionRequest.PayloadEntryR\apayload\x12;\n" +
	"\vconstraints\x18\x04 \x03(\v2\x19.nous.v1.ActionConstraintR\vconstraints\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\":\n" +
	"\x10ActionConstraint\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value2\xa9\x05\n" +
	"\x04Nous\x12<\n" +
	"\aExtract\x12\x17.nous.v1.ExtractRequest\x1a\x18.nous.v1.ExtractResponse\x12?\n" +
	"\bEvaluate\x12\x18.nous.v1.EvaluateRequest\x1a\x19.nous.v1.EvaluateResponse\x12T\n" +
	"\x0fListCommitments\x12\x1f.nous.v1.ListCommitmentsRequest\x1a .nous.v1.ListCommitmentsResponse\x12C\n" +
	"\rGetCommitment\x12\x1d.nous.v1.GetCommitmentRequest\x1a\x13.nous.v1.Commitment\x12N\n" +
	"\rListDecisions\x12\x1d.nous.v1.ListDecisionsRequest\x1a\x1e.nous.v1.ListDecisionsResponse\x12=\n" +
	"\vGetDecision\x12\x1b.nous.v1.GetDecisionRequest\x1a\x11.nous.v1.Decision\x12Z\n" +
	"\x11ListInterventions\x12!.nous.v1.ListInterventionsRequest\x1a\".nous.v1.ListInterventionsResponse\x12I\n" +
	"\x0fGetIntervention\x12\x1f.nous.v1.GetInterventionRequest\x1a\x15.nous.v1.Intervention\x12Q\n" +
	"\x13ResolveIntervention\x12#.nous.v1.ResolveInterventionRequest\x1a\x15.nous.v1.InterventionB2Z0github.com/felixgeelhaar/nous/api/nous/v1;nousv1b\x06proto3"

var (
	file_api_nous_v1_nous_proto_rawDescOnce sync.Once
	file_api_nous_v1_nous_proto_rawDescData []byte
)

func file_api_nous_v1_nous_proto_rawDescGZIP() []byte {
	file_api_nous_v1_nous_proto_rawDescOnce.Do(func() {
		file_api_nous_v1_nous_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_nous_v1_nous_proto_rawDesc), len(file_api_nous_v1_nous_proto_rawDesc)))
	})
	return file_api_nous_v1_nous_proto_rawDescData
}

var file_api_nous_v1_nous_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_api_nous_v1_nous_proto_goTypes = []any{
	(*ExtractRequest)(nil),             // 0: nous.v1.ExtractRequest
	(*ExtractResponse)(nil),            // 1: nous.v1.ExtractResponse
	(*EvaluateRequest)(nil),            // 2: nous.v1.EvaluateRequest
	(*EvaluateResponse)(nil),           // 3: nous.v1.EvaluateResponse
	(*ListCommitmentsRequest)(nil),     // 4: nous.v1.ListCommitmentsRequest
	(*ListCommitmentsResponse)(nil),    // 5: nous.v1.ListCommitmentsResponse
	(*GetCommitmentRequest)(nil),       // 6: nous.v1.GetCommitmentRequest
	(*Commitment)(nil),                 // 7: nous.v1.Commitment
	(*ListDecisionsRequest)(nil),       // 8: nous.v1.ListDecisionsRequest
	(*ListDecisionsResponse)(nil),      // 9: nous.v1.ListDecisionsResponse
	(*GetDecisionRequest)(nil),         // 10: nous.v1.GetDecisionRequest
	(*Decision)(nil),                   // 11: nous.v1.Decision
	(*ListInterventionsRequest)(nil),   // 12: nous.v1.ListInterventionsRequest
	(*ListInterventionsResponse)(nil),  // 13: nous.v1.ListInterventionsResponse
	(*GetInterventionRequest)(nil),     // 14: nous.v1.GetInterventionRequest
	(*ResolveInterventionRequest)(nil), // 15: nous.v1.ResolveInterventionRequest
	(*Intervention)(nil),               // 16: nous.v1.Intervention
	(*SourceRef)(nil),                  // 17: nous.v1.SourceRef
	(*EntityRef)(nil),                  // 18: nous.v1.EntityRef
	(*ActionRequest)(nil),              // 19: nous.v1.ActionRequest
	(*ActionConstraint)(nil),           // 20: nous.v1.ActionConstraint
	nil,                                // 21: nous.v1.Decision.InputsEntry
	nil,                                // 22: nous.v1.Decision.OutcomeEntry
	nil,                                // 23: nous.v1.ActionRequest.PayloadEntry
	(*durationpb.Duration)(nil),        // 24: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),      // 25: google.protobuf.Timestamp
}
var file_api_nous_v1_nous_proto_depIdxs = []int32{
	17, // 0: nous.v1.ExtractRequest.source_refs:type_name -> nous.v1.SourceRef
	24, // 1: nous.v1.EvaluateRequest.signal_lookback:type_name -> google.protobuf.Duration
	25, // 2: nous.v1.ListCommitmentsRequest.due_by:type_name -> google.protobuf.Timestamp
	7,  // 3: nous.v1.ListCommitmentsResponse.commitments:type_name -> nous.v1.Commitment
	17, // 4: nous.v1.Commitment.source_refs:type_name -> nous.v1.SourceRef
	18, // 5: nous.v1.Commitment.entities:type_name -> nous.v1.EntityRef
	25, // 6: nous.v1.Commitment.due_at:type_name -> google.protobuf.Timestamp
	25, // 7: nous.v1.Commitment.last_evaluated_at:type_name -> google.protobuf.Timestamp
	25, // 8: nous.v1.Commitment.created_at:type_name -> google.protobuf.Timestamp
	25, // 9: nous.v1.Commitment.updated_at:type_name -> google.protobuf.Timestamp
	11, // 10: nous.v1.ListDecisionsResponse.decisions:type_name -> nous.v1.Decision
	17, // 11: nous.v1.Decision.context_refs:type_name -> nous.v1.SourceRef
	21, // 12: nous.v1.Decision.inputs:type_name -> nous.v1.Decision.InputsEntry
	22, // 13: nous.v1.Decision.outcome:type_name -> nous.v1.Decision.OutcomeEntry
	25, // 14: nous.v1.Decision.created_at:type_name -> google.protobuf.Timestamp
	25, // 15: nous.v1.ListInterventionsRequest.since:type_name -> google.protobuf.Timestamp
	16, // 16: nous.v1.ListInterventionsResponse.interventions:type_name -> nous.v1.Intervention
	19, // 17: nous.v1.Intervention.suggested_action:type_name -> nous.v1.ActionRequest
	25, // 18: nous.v1.Intervention.triggered_at:type_name -> google.protobuf.Timestamp
	25, // 19: nous.v1.Intervention.resolved_at:type_name -> google.protobuf.Timestamp
	23, // 20: nous.v1.ActionRequest.payload:type_name -> nous.v1.ActionRequest.PayloadEntry
	20, // 21: nous.v1.ActionRequest.constraints:type_name -> nous.v1.ActionConstraint
	0,  // 22: nous.v1.Nous.Extract:input_type -> nous.v1.ExtractRequest
	2,  // 23: nous.v1.Nous.Evaluate:input_type -> nous.v1.EvaluateRequest
	4,  // 24: nous.v1.Nous.ListCommitments:input_type -> nous.v1.ListCommitmentsRequest
	6,  // 25: nous.v1.Nous.GetCommitment:input_type -> nous.v1.GetCommitmentRequest
	8,  // 26: nous.v1.Nous.ListDecisions:input_type -> nous.v1.ListDecisionsRequest
	10, // 27: nous.v1.Nous.GetDecision:input_type -> nous.v1.GetDecisionRequest
	12, // 28: nous.v1.Nous.ListInterventions:input_type -> nous.v1.ListInterventionsRequest
	14, // 29: nous.v1.Nous.GetIntervention:input_type -> nous.v1.GetInterventionRequest
	15, // 30: nous.v1.Nous.ResolveIntervention:input_type -> nous.v1.ResolveInterventionRequest
	1,  // 31: nous.v1.Nous.Extract:output_type -> nous.v1.ExtractResponse
	3,  // 32: nous.v1.Nous.Evaluate:output_type -> nous.v1.EvaluateResponse
	5,  // 33: nous.v1.Nous.ListCommitments:output_type -> nous.v1.ListCommitmentsResponse
	7,  // 34: nous.v1.Nous.GetCommitment:output_type -> nous.v1.Commitment
	9,  // 35: nous.v1.Nous.ListDecisions:output_type -> nous.v1.ListDecisionsResponse
	11, // 36: nous.v1.Nous.GetDecision:output_type -> nous.v1.Decision
	13, // 37: nous.v1.Nous.ListInterventions:output_type -> nous.v1.ListInterventionsResponse
	16, // 38: nous.v1.Nous.GetIntervention:output_type -> nous.v1.Intervention
	16, // 39: nous.v1.Nous.ResolveIntervention:output_type -> nous.v1.Intervention
	31, // [31:40] is the sub-list for method output_type
	22, // [22:31] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_api_nous_v1_nous_proto_init() }
func file_api_nous_v1_nous_proto_init() {
	if File_api_nous_v1_nous_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_nous_v1_nous_proto_rawDesc), len(file_api_nous_v1_nous_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_nous_v1_nous_proto_goTypes,
		DependencyIndexes: file_api_nous_v1_nous_proto_depIdxs,
		MessageInfos:      file_api_nous_v1_nous_proto_msgTypes,
	}.Build()
	File_api_nous_v1_nous_proto = out.File
	file_api_nous_v1_nous_proto_goTypes = nil
	file_api_nous_v1_nous_proto_depIdxs = nil
}
